---
title: "Multimap report"
title-block-banner: '#446e9b'
author: "Nicolas Poncelet"
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: false
date:  today
lang: en
format: 
  html:
    html-math-method: mathml
    html_document: default
    theme: spcacelab
    page-layout: full
    embed-resources: true
    code-tools:
      source: true
      toggle: true
    code-fold: true
    code-copy: true
    code_download: true
    toc: true
    toc-location: left
    number-sections: true
    smooth-scroll: true
---

```{r,echo=TRUE, include=FALSE}

#Nettoyage de la cache.

rm(list=ls()) 

options(dplyr.summarise.inform = FALSE)

```


```{r,package,echo=TRUE, include=FALSE}

#Chargement des packages nécessaires.

library(DT) # Tableau interactif.
library(ggplot2)
library(heatmaply) # création de heatmap interactive.
library(kableExtra) # Tableau interactif.
library(plotly) # Rend les graphes interactifs.
library(tidyverse)

```



```{r, load_raw_data}

df_reference <- read.delim("references.csv",sep = ";")

df_fastq <- read.delim("fastq.csv",sep = ";")

df_flagstat <- read.delim("flagstat.csv",sep = ";")

```



```{r,reference_table}
df_reference%>%
kbl()%>%
kable_styling("striped")
```



```{r,fastq_table}
df_fastq%>%
  select(Isolat,Total_reads)%>%
kbl()%>%
kable_styling("striped")
```



```{r,heatmap}

df_long <- df_flagstat%>%
  select(Isolat,Reference,Properly_paired_percentage)

df_W<-pivot_wider(df_long, 
                  names_from = Reference, 
                  values_from = Properly_paired_percentage)


df_W <- df_W %>% 
        remove_rownames %>% 
        column_to_rownames(var="Isolat")

mat_genome<-as.matrix(df_W)

mapping_matrix<-heatmaply(mat_genome,
  seriate = "OLO",show_dendrogram = c(T, F), fontsize_col = 8, fontsize_row = 8,
  plot_method = "plotly",k_row=NA
)

mapping_matrix

```

