# Configuration file for Multimap pipeline
# -----------------------------------------
# Input directories (specify paths to data files):

fastq_dir: "/shared/home/nponcelet/lolium_gbs/03_Test_multimap/Test_data/Fastq"
reference_dir: "/shared/home/nponcelet/lolium_gbs/03_Test_multimap/Test_data/Reference"

conda_env: "Config/multimap_conda.yaml"

# Output directory (specify where results will be saved):

analysis_dir: "/shared/home/nponcelet/lolium_gbs/03_Test_multimap/Test_data"

# Mapping target: choose between whole genome or genes

mapping:
  map_to_genome: true